import type { DailyLog } from '@/api/trips'

export const SAMPLE_LOG: DailyLog = {
  date: '2026-09-26',
  from_location: 'Chicago, IL',
  to_location: 'Griggsville, IL',
  total_miles: 457.7,
  totals_minutes: { off_duty: 480, sleeper: 210, driving: 660, on_duty: 90 },
  segments: [
    {
      status: 'off_duty',
      start: '',
      end: '',
      start_minute: 0,
      end_minute: 480,
      location: 'Chicago, IL',
      note: '',
    },
    {
      status: 'on_duty',
      start: 'a',
      end: '',
      start_minute: 480,
      end_minute: 510,
      location: 'Chicago, IL',
      note: 'Pre-trip inspection',
    },
    {
      status: 'driving',
      start: 'b',
      end: '',
      start_minute: 510,
      end_minute: 791,
      location: 'Chicago, IL',
      note: 'Driving to pickup',
    },
    {
      status: 'on_duty',
      start: 'c',
      end: '',
      start_minute: 791,
      end_minute: 851,
      location: 'Indianapolis, IN',
      note: 'Pickup',
    },
    {
      status: 'driving',
      start: 'd',
      end: '',
      start_minute: 851,
      end_minute: 1230,
      location: 'Indianapolis, IN',
      note: 'Driving to dropoff',
    },
    {
      status: 'sleeper',
      start: 'e',
      end: '',
      start_minute: 1230,
      end_minute: 1440,
      location: 'Griggsville, IL',
      note: '10-hour rest',
    },
  ],
  remarks: [
    {
      time: 'a',
      minute: 480,
      location: 'Chicago, IL',
      note: 'Pre-trip inspection',
      status: 'on_duty',
    },
    {
      time: 'b',
      minute: 510,
      location: 'Chicago, IL',
      note: 'Driving to pickup',
      status: 'driving',
    },
    { time: 'c', minute: 791, location: 'Indianapolis, IN', note: 'Pickup', status: 'on_duty' },
    {
      time: 'd',
      minute: 851,
      location: 'Indianapolis, IN',
      note: 'Driving to dropoff',
      status: 'driving',
    },
    {
      time: 'e',
      minute: 1230,
      location: 'Griggsville, IL',
      note: '10-hour rest',
      status: 'sleeper',
    },
  ],
  on_duty_minutes: 750,
  cycle_used_minutes: 1950,
  cycle_available_minutes: 2250,
}
